# Generated by Django 4.1.2 on 2022-10-11 16:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import localflavor.br.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('salario', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('cpf', localflavor.br.models.BRCPFField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('funcionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='funcionarios.funcionario')),
                ('nome_social', models.CharField(max_length=200)),
                ('estado_civil', models.CharField(choices=[('S', 'Solteiro'), ('C', 'Casado'), ('D', 'Divorciado'), ('V', 'Viúvo')], max_length=1)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=500)),
                ('funcionarios', models.ManyToManyField(to='funcionarios.funcionario')),
            ],
        ),
    ]
