# Generated by Django 4.1.2 on 2022-10-11 16:46

from django.db import migrations, models
import localflavor.br.models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='departamento',
            name='nome',
            field=models.CharField(default='Default', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=localflavor.br.models.BRCPFField(max_length=14, verbose_name='CPF'),
        ),
    ]
