# Generated by Django 4.1.2 on 2022-10-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_departamento_nome_alter_funcionario_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='descricao',
            field=models.CharField(max_length=500, verbose_name='Descrição'),
        ),
    ]
