# Generated by Django 4.1.2 on 2022-10-11 18:28

from django.db import migrations, models
import funcionarios.validators.datefield


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_alter_departamento_funcionarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='data_nascimento',
            field=models.DateField(validators=[funcionarios.validators.datefield.validate_lt_date]),
        ),
    ]
