# Generated by Django 4.1.2 on 2022-10-11 18:35

from django.db import migrations
import ecommerce.my_fields


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0005_alter_perfil_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=ecommerce.my_fields.BRCPFFieldNumeric(max_length=14, verbose_name='CPF'),
        ),
    ]
